replicaCount: 2

image:
  repository: 741448960679.dkr.ecr.us-east-1.amazonaws.com/results_service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: results.smartmedia.local
      paths:
        - path: /
          pathType: Prefix

env:
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: results-config
        key: db_host
  - name: DB_PORT
    value: "3306"
  - name: DB_NAME
    value: "mydatabase"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: results-secret
        key: db_user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: results-secret
        key: db_password

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
