apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    app: media-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: media-service-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: media-service-config
                  key: DB_NAME
            - name: UPLOAD_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: media-service-config
                  key: UPLOAD_BUCKET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_PASSWORD
