trigger:
  branches:
    include: [ main ]
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.3.5'
  - script: |
      cd infra
      terraform init
      terraform apply -auto-approve
    displayName: 'Terraform'
# add Docker build, Helm deploy steps