pipeline {
  agent any
  stages {
    stage('Terraform Init') { steps { dir('infra') { sh 'terraform init' } } }
    stage('Terraform Apply') { steps { dir('infra') { sh 'terraform apply -auto-approve' } } }
    stage('Build & Push Images') { /* docker build/push */ }
    stage('Deploy Helm') { /* helm upgrade */ }
  }
}